In [17]:
# Init 

import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)

float_arr1 = arr1.astype(np.float32)
print(float_arr1.dtype)
print(float_arr1)

str_arr2 = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
print(str_arr2)
print(str_arr2.dtype)

str_arr2_to_float = str_arr2.astype(float)
print(str_arr2_to_float)
print(str_arr2_to_float.dtype)

int_arr3_range = np.arange(10)
print(int_arr3_range)
print(int_arr3_range.dtype)

int_arr3_as_float = int_arr3_range.astype(float_arr1.dtype)
print(int_arr3_as_float)
print(int_arr3_as_float.dtype)

zeros_uint32 = np.zeros(8, dtype="u4")
print(zeros_uint32)
print(zeros_uint32.dtype)

[1 2 3 4 5]
int64
float32
[1. 2. 3. 4. 5.]
[b'1.25' b'-9.6' b'42']
|S4
[ 1.25 -9.6  42.  ]
float64
[0 1 2 3 4 5 6 7 8 9]
int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32
[0 0 0 0 0 0 0 0]
uint32


In [24]:
# Arithmetic operations

arr4 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr4)
print(arr4.dtype)

print(arr4 * arr4)
print(arr4 - arr4)
print(1 / arr4)

arr5 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr5 > arr4)

[[1. 2. 3.]
 [4. 5. 6.]]
float64
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[False  True False]
 [ True False  True]]


In [47]:
# Indexing and slicing

arr6 = np.arange(10)
arr6_slice = arr6[5:8]

print(arr6)
print(arr6_slice)

arr6[6] = 69

print(arr6)
print(arr6_slice)

arr6_slice_copy = arr6[5:8].copy()

arr6[6] = 6

print(arr6)
print(arr6_slice)
print(arr6_slice_copy)

arr7_2_by_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr7_2_by_3[0][2])
print(arr7_2_by_3[0, 2])

arr8_2_by_2_by_3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr8_2_by_2_by_3)
print(arr8_2_by_2_by_3[0])

arr8_0_old_values = arr8_2_by_2_by_3[0].copy()

arr8_2_by_2_by_3[0] = 69
print(arr8_2_by_2_by_3)

arr8_2_by_2_by_3[0] = arr8_0_old_values
print(arr8_2_by_2_by_3)
print(arr8_2_by_2_by_3[0, 0])


[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4  5 69  7  8  9]
[ 5 69  7]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 5 69  7]
3
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[69 69 69]
  [69 69 69]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[1 2 3]


In [50]:
# Indexing with slices

arr7_2_by_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr7_2_by_3[:2])
print(arr7_2_by_3[:2, 1:])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
